theme: jekyll-theme-cayman
title: Football Scorer Guide
description: Find all the necessary information, from commands to usage, to invites for the Football Scorer here! All updates will also be posted periodically here!
